config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  devise_for :users
  resources :users do 
    resources :likes, controller: 'user/likes', only: [:create, :destroy, :new]
    get '/all_likes/:liked_item', controller: 'user/likes', action: 'show_all_likes', as: 'show_all_likes'
    get '/all_comments/:liked_item', controller: 'user/comments', action: 'show_all_comments', as: 'show_all_comments'
  end
  resources :companies do
    resources :teams, controller: 'company/teams' do
      resources :posts, controller: 'company/posts' do 
        resources :comments, controller: 'user/comments', except: [:show, :index]
      end
    end
  end
  root 'teams#index'
end  

app/models/company.rb
class Company
  include Mongoid::Document
  include Mongoid::Timestamps
  
  field :name, type: String

  has_many :users
  has_many :teams, :class_name => 'Company::Team', dependent: :destroy
end

app/models/company/post.rb
class Company::Post

  include Mongoid::Document
  include Mongoid::Timestamps

  field :description, type: String
  field :receiver_id, type: Array, default: []
  field :for_team, type: Boolean, default: false

  belongs_to :team, index: true, :class_name => 'Company::Team'
  belongs_to :user, index: true, :class_name => 'User'
  has_many :likes, :class_name => 'User::Like', as: :likeable, dependent: :destroy
  has_many :comments, :class_name => 'User::Comment', dependent: :destroy

  validates :user, :team, :description, presence: true
end

app/models/company/team.rb
class Company::Team

  include Mongoid::Document
  include Mongoid::Timestamps
  
  field :name, type: String

  belongs_to :company, :class_name => 'Company'
  has_many :posts, :class_name => 'Company::Post'
  
end

app/controllers/company/posts_controller.rb
class Company::PostsController < ApplicationController

  before_action :set_company
  before_action :set_team
  before_action :set_post, only: [:edit, :update, :destroy]

  def index
  end

  def create
    @post = current_user.posts.new(post_params)
    @post.team = @team
    @post.for_team = true
    if @post.save
      flash.now[:notice] = 'Post Created'
    else
      flash.now[:alert] = @post.errors.full_messages.join(', ')
    end
  end

  def destroy
    if @post.destroy
      flash.now[:notice] = 'Post Destroyed'
    else
      flash.now[:alert] = @post.errors.full_messages.join(', ')
    end
  end

  def edit
  end

  def update
    if @post.update(post_params)
      flash.now[:notice] = 'Post Updated'
      flash.now[:alert] = @post.errors.full_messages.join(', ')
    end
    render partial: 'all_posts'
  end

  private

  def post_params
    params.require(:company_post).permit(:description, :receiver_id)
  end

  def set_post
    @post = @team.posts.find(params[:id])
  end

  def set_team
    @team = Company::Team.find(params[:team_id])
  end

end

app/controllers/company/teams_controller.rb
class Company::TeamsController < ApplicationController

  before_action :set_company
  before_action :set_team, except: [:index]
  
  def index
  end

  def show
  end

  private

  def set_team
    @team = Company::Team.find(params[:team_id] || params[:id])
  end
end

app/views/company/posts/_all_posts.js.erb
$('body').removeClass('modal-open');
$('.modal-backdrop').hide();
$('#<%=@post.id%>').html('<%= j render @post %>');

app/views/company/posts/_form.html.erb
<div style="overflow-y: auto;">
  <div id="<%=@post.id%>-edit-post-modal" class="modal fade colored-header" tabindex="-1" role="dialog">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <h3>Edit Post</h3>
          <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
        </div>
        <div class="modal-body" style="min-height: 125px;overflow-y: auto;">
          <%= form_for @post, remote: true, url: company_team_posts_path(@company, @post.team, @post), html: {class: 'form-horizontal', id: 'post-form'} do |f| %>
            <div>
              <div class="col-md-12 user-post" style="margin: 0px;">
                <div class="image" style="max-height: 53px; max-width: 48px;">
                  <%= image_tag '', size: "48x53", alt: " "%>
                </div>
                <div class="post-box">
                  <%=f.text_area :description, class: "form-control edit-post-form", placeholder: "Share an update..", size: "3x2", style:"resize: none;", id: "#{@post.id.to_s}-input"%>
                </div>
              </div>
              <div class="col-md-12 share-post">
                <div>
                  <span><%=f.submit 'Update', class: 'edit-post-btn'%></span>
                </div>
              </div>
              <div class="col-mda-12" id ="thumbnail-div">
            </div>
          <%end%>
        </div>
      </div>
    </div>
  </div>
</div>
</div>

<script>
    $('.edit-post-form').trigger('propertychange');
</script>

app/views/company/posts/_post.html.erb
<style>
  a:focus, a:hover, a:active {
    color: #fe8637;
  }
</style>
<script>
  $(document).on('turbolinks:load', function() {
    text = ""
    $('#<%=post.id%>').find('.inner').each(function() { 
     text += $(this).text();
     text += " " 
    })
    $('#<%=post.id%>').find('.inner').first().replaceWith($("<div>", {class: 'more', text: text}));
    $('#<%=post.id%>').find('.inner').remove();
    var showWord = 75;
    var ellipsestext = "...";
    var moretext = "show more";
    var lesstext = "show less";
    
    $('#<%=post.id%>').find('.more').each(function() {
        var content = $(this).html();
        if(content.split(' ').length > showWord) {
 
            var limitedContent = content.split(' ').slice(0, showWord).join(' ')  
            var hiddenContent = content.split(' ').slice(showWord, content.split(' ').length).join(' ')

            var html = limitedContent + '<span class="moreellipses">' + ellipsestext + '</span><span class="morecontent"><span>' + ' ' + hiddenContent + '</span><a href="" class="morelink">' + moretext + '</a></span>';
 
            $(this).html(html);
        }
    });
    $('#<%=post.id%>').find(".morelink").click(function(){
        if($(this).hasClass("less")) {
            $(this).removeClass("less");
            $(this).html(moretext);
        } else {
            $(this).addClass("less");
            $(this).html(lesstext);
        }
        $(this).parent().prev().toggle();
        $(this).prev().toggle();
        return false;
    });
 debugger
    $('.employee_comment_description').unbind().keypress(function(e){
      $(this).css('height','auto');
      $(this).height(this.scrollHeight);
      if(e.which == 13){
        $(this).closest('form').submit();
      }
    });
    
    $('.load-more-comments').hide();
    $('.user-comment-post').hide();
    $('.comment-post').hide();
    $('.comment-btn').unbind().click(function() {
      $(this).parents('.user-post').next().find('.user-comment-post').toggle();
      $(this).parents('.user-post').next().parent().next().find('.comment-post').slice(0,3).toggle();
      $(this).parents('.user-post').next().parent().next().find('.comment-post').slice(3).hide();
      $(this).parents('.user-post').parent().next().find('.subcomment-post').hide();
      $(this).parents('.user-post').parent().next().find('.user-comment-subcomment').hide();
      if ($(this).parents('.user-post').next().parent().next().find('.comment-post:visible').length) {
        $(this).parents('.user-post').next().parent().next().find('.load-more-comments').show();
      } else {
        $(this).parents('.user-post').next().parent().next().find('.load-more-comments').hide();
      }
    })

  });
</script>
<%@post = post if post%>
<div class="user-post " style="padding-left: 0px">
  <div class="image col-md-4" style="max-height: 48px; max-width: 48px;">
    <%= image_tag '', size: "48x48", alt: " "%>
  </div>
  <div class="col-md-12" style="margin-left: 15px;word-wrap: break-word;">
    <span><b style="color: #fe8637"><%=@post.user.name%></b> shared an update:</span>
    <% if @post.user == current_user ||  current_user.is_admin %>
      <ul class="nav navbar-nav navbar-right edit-post pull-right">
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" style="background-color: white;padding: 2px;">
          <b class="caret"></b></a>
            <ul class="dropdown-menu">
            <% if @post.user == current_user %>
              <li><%= link_to 'Edit Post', edit_company_team_post_path(@company, @post.team, @post), remote: true %></li>
            <%end%>
              <li><%= link_to 'Delete Post', company_team_post_path(@company, @post.team, @post), method: :delete, remote: true %></li>
            </ul>
        </li>
      </ul>
    <%end%>
    <div style="margin-bottom: 8px;"><%=time_ago_in_words(@post.created_at) + " ago"%>&nbsp;&nbsp;<i class="fa fa-globe"></i></div>
      <%@post.description.split(' ').each do |desc|%>
        <%object = LinkThumbnailer.generate(desc) rescue nil%>
        <%if desc.match(/(http).*[.](JPG)$|(http).*[.](tif)$|(http).*[.](png)$|(http).*[.](jpg)$|(http).*[.](bmp)$|(http).*[.](gif)$|(http).*[.](jpeg)$/i)%>
           <div><img poster="" src=<%=desc%> style="max-width: 312px;max-height: 161px;" controls="true"></img></div><br>
        <%elsif desc.match(/(http).*[.](mp4)$|(http).*[.](webm)$|(http).*[.](flv)$|(http).*[.](vob)$|(http).*[.](mpg)$|(http).*[.](mp2)$|(http).*[.](mpeg)$|(http).*[.](mpe)$|(http).*[.](mpv)$|(http).*[.](mpg)$|(http).*[.](mpeg)$|(http).*[.](m2v)$|(http).*[.](m4p)$/i)%>
           <div><video poster="" src=<%=desc%> style="max-width: 312px;max-height: 161px;" controls="true"></video></div><br>
        <%elsif object%>
          <br>
          <span style="font-weight: bold;"><%=object.title%></span> <br> 
          <a style="color:#33adff;" href=<%=desc%> target="_blank"><span><%=object.description.split(' ').slice(0, 25).join(' ')%></span></a> <br><br>
          <%if object.videos.first %>
            <%if object.videos.first.src.include?('www.youtube.com')%>
              <div><iframe style="max-width: 312px;max-height: 161px;" src=<%=object.videos.first.src%> frameborder="0" allowfullscreen></iframe></div><br>
            <%else%>
              <div><video poster="" src=<%=object.videos.first.src%> style="max-width: 312px;max-height: 161px;" controls="true"></video></div><br>
            <%end%>
          <%elsif object.images.first %>
            <div><%=image_tag object.images.first.src, alt: " ", style: "max-width: 312px;max-height: 161px;"%></div><br>
          <%end%>
        <%else%>
          <span class="inner"><%=desc%></span>
        <%end%>
      <%end%>
    <div class="post-actions col-md-12">
      <%@employee_post_likes = User::Like.where(post_id: @post.id, user_id: current_user.id)%>
      <%if @employee_post_likes.present?%>
        <%@like=@employee_post_likes.first.id.to_s%>
      <%end%>
      <% if @employee_post_likes.count.eql?(0) %>
        <%=link_to 'Like', user_likes_path(current_user, @post), method: :post, remote: true, class: "like-btn"%></span>
      <% else%>
        <%=link_to 'Unlike', user_like_path(current_user, @like, @post), method: :delete, remote: true, class: "like-btn"%></span>
      <%end%>
      <%=link_to 'Comment', '', remote: true, class: "comment-btn show_comment"%>
      <%=link_to '', user_show_all_likes_path(current_user, @post), remote: true, class: "fa fa-thumbs-o-up thumsup-icon", style: "color: black"%>
      <span class="likes_count"><%=User::Like.where(post_id: @post.id).count%></span>
      <%=link_to '', '', remote: true, class: "fa fa-comment-o comment-icon", style: "color: black"%>
      <span class="comments_count"><%=User::Comment.where(post_id: @post.id, parent_comment_id: nil).count%></span>
    </div>
  </div>
</div>
<%@comment= @post.comments.new%>
 <%= form_for @comment, remote: true, url: company_team_post_comments_path(@company, @post.team, @post), html: {class: 'form-horizontal', id: 'create-comment-form'} do |f| %>
  <div class="user-comment-post" style="margin-top: 0px;">
    <div class="image" style="max-height: 53px; max-width: 48px;">
      <%= image_tag '', size: "48x53", alt: " "%>
    </div>
    <div class="post-box" style="float:right;">
      <%=f.text_area :description, class: "form-control employee_comment_description", placeholder: "Press Enter to Add Comment..", size: "3x2", style:"overflow:hidden;resize: none;width:96%"%>
      <span style="display: none;"><%=f.submit%></span>
    </div>
  </div>
<%end%>

<div id="comment_data<%=@post.id%>" style="max-height: 453px;width: 91%;overflow-y: auto;">
  <%= render partial: "user/comments/comment", collection: @post.comments.where(parent_comment_id: nil).order(created_at: :asc), as: :comment %>
</div>

app/views/company/posts/create.js.erb
$('.post_data').prepend('<%= j render @post %>');
$('#company_post_description').val('');

app/views/company/posts/destroy.js.erb
$('#<%=@post.id%>').remove();
$('#comment_data<%=@post.id%>').remove();

app/views/company/posts/edit.js.erb
id = '<%=params[:id]%>';
$('#empty').html("<%= j render partial: 'form', locals: { :@post => Company::Post.find(params[:id]) } %>");
$('#<%=@post.id%>-edit-post-modal').modal();
$('.edit-post-form').unbind().keypress(function(e){
  $(this).css('height','auto');
  $(this).height(this.scrollHeight);
  });
$('#thumbnail-div').hide();
$('.modal').click(function() {
  if ($('.multiselect-container.dropdown-menu').is(':visible')) {
    $(this).find('.modal-body').css('min-height','113px');
    $(this).closest('.modal').find('.modal-button').show();
  } 
});
$('.save-custom-btn').find('a').click(function() {
  if ($('#<%=@post.id%>-share-modal').find('.modal-body').find('button.multiselect.dropdown-toggle').attr('title')=="None selected") {
    $('.save-custom-btn').parent().prev().children('.error').show();
  } else {
    emp_array = $('#<%=@post.id%>-share-modal').find('.modal-body').find('button.multiselect.dropdown-toggle').attr('title')
    $('.save-custom-btn').parent().prev().children('.error').hide();
    $('.edit_custom_name_field').val(emp_array);
    $('#<%=@post.id%>-share-modal').find('.close').click();
    $('#<%=@post.id%>-edit-post-modal').show();
    $('.edit-share-btn').find('a').text('Specific People');
    $('.edit-share-btn').find('i').attr('class', 'fa fa-asterisk');
  }
});
$('a.load-more-posts').hide();
$('.share_status').keypress(function(e){
  $(this).css('height','auto');
  $(this).height(this.scrollHeight);
 });
$('.edit-post-btn').unbind().click(function() {
  $('#thumbnail-div').hide();
  $('#thumbnail-div').empty();
  $('.modal-header button.close').trigger('click');
  $('.modal-backdrop').fadeOut();
  $(this).parents('.share-post').find('.share_with_field').val($(this).parent().next().text().trim());
  $('.share-post').find('.status-thumbnail').remove();
  $('.modal-header button.close').trigger('click');
  $('.modal-backdrop').fadeOut();
});

$('.edit-post-form').bind('input propertychange', function() {
  if(!$('#thumbnail-div').find('.status-thumbnail').length) {
    var _this = this;
    request = $.ajax({
      type: "GET",
      url: "/thumbnail",
      data: $(_this).val(),
      success: function (result) {
      },
      error: function (){
      }
     });
    } else if($('.edit-post-form').val()=="") {
      $('#thumbnail-div').empty();
      $('#thumbnail-div').hide();
    }
  });

app/views/company/posts/index.html.erb
<%=render partial: 'shared/team_cards'%>
<div id="empty"></div>
<div class="col-md-12 container" style="margin-bottom: 5%">
  <div class="col-md-9 col-md-offset-1" style="margin-bottom: 5%;">
    <% @post= @team.posts.new %>
    <%= form_for @post, remote: true, url: company_team_posts_path(@company, @team), html: {class: 'form-horizontal', id: 'create-post-form'} do |f| %>
        <div>
          <div class="col-md-12 user-post">
            <div class="image">
              <%= image_tag '', size: "64x72", alt: " " %>
            </div>
            <div class="post-box">
              <%= f.text_area :description, class: "form-control share_status", placeholder: "Share an update..", size: "3x3", style: "overflow:hidden;resize: none;" %>
            </div>
          </div>
          <div class="col-md-12 share-post">
            <div>
              <span><%= f.submit 'Post', class: 'post-btn' %></span>
              <span class="share-btn"><i class="fa fa-home"></i>&nbsp;<%= link_to 'Share', '', remote: true %></span>
            </span>
            </div>
          </div>
          <div class="col-mda-12" id="thumbnail-div">
          </div>
        </div>
    <% end %>
  </div>
  <div class="post_data">
    <% @posts = @team.posts.order(updated_at: :desc).where(for_team: true) %>
    <%if @posts.present?%>
      <%@posts.each do |post|%>
        <div class="col-md-9 col-md-offset-1" id=<%=post.id%>>
          <%=render partial: 'post', locals: { post: post } %>
        </div>
      <%end%>
    <%end%>
  </div>
</div>