config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  devise_for :users
  resources :users do 
    resources :likes, controller: 'user/likes', only: [:create, :destroy, :new]
    get '/all_likes/:liked_item', controller: 'user/likes', action: 'show_all_likes', as: 'show_all_likes'
    get '/all_comments/:liked_item', controller: 'user/comments', action: 'show_all_comments', as: 'show_all_comments'
  end
  resources :companies do
    resources :teams, controller: 'company/teams' do
      resources :posts, controller: 'company/posts' do 
        resources :comments, controller: 'user/comments', except: [:show, :index]
      end
    end
  end
  root 'teams#index'
end  

app/models/user.rb
class User
  include Mongoid::Document
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  ## Database authenticatable
  field :name, type: String, default: ""
  field :is_admin, type: Boolean, default: false
  field :email, type: String, default: ""
  field :gender, type: String, default: 'Male'
  field :encrypted_password, type: String, default: ""

  ## Recoverable
  field :reset_password_token,   type: String
  field :reset_password_sent_at, type: Time

  ## Rememberable
  field :remember_created_at, type: Time

  ## Trackable
  field :sign_in_count,      type: Integer, default: 0
  field :current_sign_in_at, type: Time
  field :last_sign_in_at,    type: Time
  field :current_sign_in_ip, type: String
  field :last_sign_in_ip,    type: String

  has_one :company, :class_name => 'Company'
  has_many :posts, :class_name => 'Company::Post'
  has_many :likes, :class_name => 'User::Like'
  has_many :comments, :class_name => 'User::Comment'

  ## Confirmable
  # field :confirmation_token,   type: String
  # field :confirmed_at,         type: Time
  # field :confirmation_sent_at, type: Time
  # field :unconfirmed_email,    type: String # Only if using reconfirmable

  ## Lockable
  # field :failed_attempts, type: Integer, default: 0 # Only if lock strategy is :failed_attempts
  # field :unlock_token,    type: String # Only if unlock strategy is :email or :both
  # field :locked_at,       type: Time
end

app/models/user/comment.rb
class User::Comment

  include Mongoid::Document
  include Mongoid::Timestamps

  field :description, type: String

  belongs_to :post, :class_name => 'Company::Post'
  belongs_to :user, :class_name => 'User'
  has_many :subcomments, class_name: "User::Comment", foreign_key: "parent_comment_id", dependent: :destroy
  belongs_to :parent_comment, class_name: "User::Comment", foreign_key: "parent_comment_id"

  validates :description, presence: true

end

app/models/user/like.rb
class User::Like

  include Mongoid::Document
  include Mongoid::Timestamps

  belongs_to :user, :class_name => 'User'
  belongs_to :comment, :class_name => 'User::Comment'
  belongs_to :post, :class_name => 'Company::Post'
  belongs_to :likeable, polymorphic: true

  validates :user, presence: true
  validates_uniqueness_of :post_id, :case_sensitive => false, scope: :employee_id

end

app/controllers/user/comments_controller.rb
class User::CommentsController < ApplicationController

  before_action :set_company
  before_action :set_post, except: [:show_all_comments]
  before_action :set_comment, only: [:edit, :update, :destroy]

  def new
    @comment = @post.comments.new
  end

  def create
    @comment = current_user.comments.new(comment_params)
    @comment.post = @post
    @comment.user = @post.user
    if params.require(:user_comment).permit(:parent_comment).present?
      @comment.parent_comment_id = params.require(:user_comment).require(:parent_comment)
    else
    end
    if @comment.save
      flash.now[:notice] = 'Comment Created'
    else
      flash.now[:alert] = @comment.errors.full_messages.join(', ')
    end
  end

  def edit
  end

  def update
    if @comment.update(comment_params)
      flash.now[:notice] = 'Comment Updated'
    else
      flash.now[:alert] = @comment.errors.full_messages.join(', ')
    end
    render partial: 'all_comments'
  end

  def destroy
    if @comment.destroy
      flash.now[:notice] = 'Comment Destroyed'
    else
      flash.now[:alert] = @comment.errors.full_messages.join(', ')
    end
  end

  def show_all_comments
    if (Company::Post.find(params[:liked_item]).present? rescue nil)
      @post_item = Company::Post.find(params[:liked_item])
    else
      @comment_item = User::Comment.find(params[:liked_item])
    end
  end

  private

  def comment_params
    params.require(:user_comment).permit(:description)
  end

  def set_post
    @post = Company::Post.find(params[:post_id])
  end

  def set_params
    @comment = @employee.comments.find(params[:id])
  end

  def set_comment
    @comment = @post.comments.find(params[:id])
  end

end

app/controllers/user/likes_controller.rb
class User::LikesController < ApplicationController

  before_action :set_company
  before_action :set_liked_item, except: [:show_all_likes]
  before_action :set_like , only: [:destroy]

  def new
  end

  def create
    @like = current_user.likes.new
    @like.post = @post
    @like.comment = @comment
    if current_user.likes.where(post_id: @post.id.to_s).blank?
      @like.save(validate: false)
      render 'like'
    else
      head status: 200
    end
  end

  def destroy
    @like.destroy
    render 'unlike'
  end

  def show_all_likes
    if (Company::Post.find(params[:liked_item]).present? rescue nil)
      @post_item = Company::Post.find(params[:liked_item])
    else
      @comment_item = User::Comment.find(params[:liked_item])
    end
  end

  private

  def set_liked_item
    if (Company::Post.find(params[:format]).present? rescue nil)
      @post = Company::Post.find(params[:format])
    else
      @comment = User::Comment.find(params[:format])
    end
  end

  def set_like
    @like = current_user.likes.find(params[:id])
  end

end

app/controllers/users_controller.rb
class Users < ApplicatinController
  # before_filter :authenticate_user!

  def show
    @user = User.find(params[:id])
  end
end

app/helpers/user/registrations_helper.rb
module User::RegistrationsHelper
  def resource_name
    :user
  end

  def resource
    @resource ||= User.new
  end

  def devise_mapping
    @devise_mapping ||= Devise.mappings[:user]
  end
end

app/views/user/comments/_all_comments.js.erb
$('body').removeClass('modal-open');
$('.modal-backdrop').hide();
<%if @comment.parent_comment.present?%> 
  parent_id = '<%=@comment.parent_comment_id%>'
  $('#<%=@comment.parent_comment.try(:id)%>').find('.subcomments_count').text(<%=@comment.parent_comment.try(:subcomments).try(:count)%>)
  $('#subcomment_data'+parent_id).html('<%= j render partial: 'subcomment', collection: @comment.parent_comment.subcomments.order(created_at: :desc), as: :subcomment %>');
<%else%>
  id = '<%=params[:post_id]%>';
  $('#<%=@post.id%>').find('.comments_count').text(<%=@post.comments.where(parent_comment_id: nil).count%>)
  $('#comment_data'+id).html('<%= j render partial: :comment, collection: @post.comments.where(parent_comment_id: nil).order(created_at: :desc), as: :comment %>');
<%end%>

app/views/user/comments/_comment.html.erb
<script>
  $(function () {
      $('.comment-icon').unbind().click(function() {
          $(this).parent().find('.comment-btn').click();
          $(this).parent().find('.subcomment-btn').click();
      });
    var showWord = 36;
    var ellipsestext = "...";
    var moretext = "show more";
    var lesstext = "show less";
    
    $('#<%=comment.id%>').find('.more').each(function() {
        var content = $(this).html();
        if(content.split(' ').length > showWord) {
 
            var limitedContent = content.split(' ').slice(0, showWord).join(' ')  
            var hiddenContent = content.split(' ').slice(showWord, content.split(' ').length).join(' ')

            var html = limitedContent + '<span class="moreellipses">' + ellipsestext + '</span><span class="morecontent"><span>' + ' ' + hiddenContent + '</span><a href="" class="morelink">' + moretext + '</a></span>';
 
            $(this).html(html);
        }
    });
 
    $('#<%=comment.id%>').find(".morelink").click(function(){
        if($(this).hasClass("less")) {
            $(this).removeClass("less");
            $(this).html(moretext);
        } else {
            $(this).addClass("less");
            $(this).html(lesstext);
        }
        $(this).parent().prev().toggle();
        $(this).prev().toggle();
        return false;
    });
    $('.load-more-replies').hide();
    $('.loading-comment-indicator').hide();
    $('#<%=comment.id%>').find('.subcomments_count').text(<%=comment.subcomments.count%>)
    $('#<%=@post.id%>').find('.comments_count').text(<%=@post.comments.where(parent_comment_id: nil).count%>)
    $('.employee_subcomment_description').unbind().keypress(function(e){
      $(this).css('height','auto');
      $(this).height(this.scrollHeight);
      if(e.which == 13){
        $(this).closest('form').submit();
       }
      });
    $('.user-comment-subcomment').hide();
    $('.subcomment-post').hide();
    $('.subcomment-btn').unbind().click(function() {
      $(this).parents('.comment-post').next().find('.user-comment-subcomment').toggle();
      $(this).parents('.comment-post').next().parent().next().find('.subcomment-post').slice(0,3).toggle();
      $(this).parents('.comment-post').next().parent().next().find('.subcomment-post').slice(3).hide();
      if ($(this).parents('.comment-post').next().parent().next().find('.subcomment-post:visible').length) {
        $(this).parents('.comment-post').next().parent().next().find('.load-more-replies').show();  
      } else {
        $(this).parents('.comment-post').next().parent().next().find('.load-more-replies').hide();
      }
      
    })
    $('.load-more-comments').unbind().click(function() {
      $(this).parent().find('.comment-post:hidden').slice(0,3).show();
      $(this).find('.loading-comment-indicator').show().delay(100).fadeOut();
      if (!$(this).parent().find('.comment-post:hidden').length) {
        $(this).toggle();
      }
    });
  });
</script>
<%@comment = comment if comment%>
<%if @comment.post.comments.where(parent_comment_id: nil).count>3 && @comment.post.comments.where(parent_comment_id: nil).order(created_at: :desc).first.eql?(@comment)%>
  <div class="load-more-comments col-md-6">
    <%= link_to 'Load more comments', '', remote: true, style: "color:#fe8637"%>
    <span class="loading-comment-indicator">
    <%= image_tag("comment_loader.gif", class: "loading-indicator") %>
    </span>
  </div>
<%end%>
<div id=<%=@comment.id%>>
  <div class="col-md-12 comment-post " style="padding-left: 0px;">
    <div class="image col-md-4" style="max-height: 40px; max-width: 40px;">
      <% src = "profpic_#{@comment.user.gender.downcase}_index.jpg" %>
      <% src = @comment.user.image_url(:thumb) if (@comment.user.image_url rescue false) %>
      <%= image_tag src, size: "40x40", alt: " "%>
    </div>
    <div class="col-md-12" style="margin-left: 15px;width: 475px;word-wrap: break-word;">
      <span><b style="color: #fe8637"><%=@comment.user.name%></b></span>
      <% if @comment.user == @user || current_user.is_admin || @post.user == current_user %>
        <ul class="nav navbar-nav navbar-right edit-comment pull-right">
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" style="background-color: #f7f7f7;;padding: 2px;">
            <b class="caret"></b></a>
              <ul class="dropdown-menu">
              <% if @comment.user == current_user %>
                <li><%= link_to 'Edit comment', edit_company_team_post_comment_path(@company, @post.team, @post, @comment.id.to_s), remote: true %></li>
              <%end%>
                <li><%= link_to 'Delete comment', company_team_post_comment_path(@company, @post.team, @post, @comment.id.to_s), method: :delete, remote: true %></li>
              </ul>
          </li>
        </ul>
      <%end%>
      <br>
      <span class="more"><%=@comment.description%></span>
      <div class="comment-actions col-md-12">
        <%@user_comment_likes = User::Like.where(comment_id: @comment.id, user_id: current_user.id)%>
        <%if @user_comment_likes.present?%>
          <%@like=@user_comment_likes.first.id.to_s%>
        <%end%>
        <% if @user_comment_likes.count.eql?(0) %>
          <%=link_to 'Like', user_likes_path(current_user), method: :post, remote: true, class: "like-btn"%></span>
        <% else%>
          <%=link_to 'Unlike', user_like_path(current_user, @like), method: :delete, remote: true, class: "like-btn"%></span>
        <%end%>
        <%=link_to 'Reply', '', remote: true, class: "subcomment-btn show_comment"%>
        <%=link_to '', user_show_all_likes_path(current_user, @comment.id.to_s), remote: true, class: "fa fa-thumbs-o-up thumsup-icon", style: "color: black"%>
        <span class="likes_count"><%=User::Like.where(comment_id: @comment.id).count%></span>
        <%=link_to '', '', remote: true, class: "fa fa-comment-o comment-icon", style: "color: black"%>
        <span class="subcomments_count"></span>
        <%debugger%>
        <span style="margin-left: 9px;"><%=time_ago_in_words(@comment.created_at)%></span>
      </div>
    </div>
  </div>
  <%@subcomment= @comment.subcomments.new%>
  <%= form_for @subcomment, remote: true, url: company_team_post_comments_path(@company, @post.team, @post), html: {class: 'form-horizontal', id: 'create-subcomment-form'} do |f| %>
    <%= f.hidden_field :parent_comment, value: @comment.id%>
    <div class="col-md-12 user-comment-subcomment" style="margin-top: 0px;">
      <div class="image" style="max-height: 30px; max-width: 30px;">
        <% src = "profpic_#{current_user.gender.downcase}_index.jpg" %>
        <% src = current_user.image_url(:thumb) if (current_user.image_url rescue false) %>
        <%= image_tag src, size: "30x30", alt: " "%>
      </div>
      <div class="post-box col-md-12" style="float:right;">
        <%=f.text_area :description, class: "form-control employee_subcomment_description", placeholder: "Press Enter to Write a reply..", size: "3x1", style:"overflow:hidden;resize: none;"%><br>
        <span style="display: none;"><%=f.submit%></span>
      </div>
    </div>
  <%end%>
</div>

<div id="subcomment_data<%=@comment.id%>">
  <%= render partial: "employee/comments/subcomment", collection: @comment.subcomments.order(created_at: :asc), as: :subcomment %>
</div>

app/views/user/comments/_form.html.erb
<script>
  $(function () {
    $('#<%=@comment.id%>-edit-comment-modal').modal();
    $('.employee_comment_description').unbind().keypress(function(e){
      $(this).css('height','auto');
      $(this).height(this.scrollHeight);
      if(e.which == 13){
        $(this).closest('form').submit();
        $('.modal-header button.close').trigger('click');
       }
      });
  });
</script>

<div style="overflow-y: auto;">
  <div id="<%=@comment.id%>-edit-comment-modal" class="modal fade colored-header" tabindex="-1" role="dialog">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <h3>Edit Comment</h3>
          <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
        </div>
        <div class="modal-body" style="max-height: 450px;overflow-y: auto;">
          <%= form_for @comment, remote: true, url: company_employee_post_comment_path(@company, @employee, @post, @comment), html: {class: 'form-horizontal', id: 'edit-comment-form'} do |f| %>
            <div>
              <div class="col-md-12 user-post" style="margin-top: 0px;">
                <div class="image" style="max-height: 48px; max-width: 48px;">
                  <% src = "profpic_#{@employee.gender.downcase}_index.jpg" %>
                  <% src = @employee.user.image_url(:thumb) if (@employee.user.image_url rescue false) %>
                  <%= image_tag src, size: "48x48", alt: " "%>
                </div>
                <div class="post-box" style="float:right;">
                  <%=f.text_area :description, class: "form-control employee_comment_description", placeholder: "Press Enter to Add Comment..", size: "3x2", style:"overflow:hidden;resize: none;",id: "#{@comment.id.to_s}-input" %>
                </div>
              </div>
              <div class="col-md-12 share-post">
                <div>
                  <span style="display: none;"><%=f.submit%></span>
                  <span style="float: right;">Press Enter to Add a Comment</span>
                </div>
              </div>
            </div>
          <%end%>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/user/comments/_subcomment.html.erb
<script>
  $(function() {
      $('.comment-icon').unbind().click(function() {
          $(this).parent().find('.comment-btn').click();
          $(this).parent().find('.subcomment-btn').click();
      });
    var showWord = 20;
    var ellipsestext = "...";
    var moretext = "show more";
    var lesstext = "show less";
    
    $('#<%=subcomment.id%>').find('.more').each(function() {
        var content = $(this).html();
        if(content.split(' ').length > showWord) {
 
            var limitedContent = content.split(' ').slice(0, showWord).join(' ')  
            var hiddenContent = content.split(' ').slice(showWord, content.split(' ').length).join(' ')

            var html = limitedContent + '<span class="moreellipses">' + ellipsestext + '</span><span class="morecontent"><span>' + ' ' + hiddenContent + '</span><a href="" class="morelink">' + moretext + '</a></span>';
 
            $(this).html(html);
        }
    });
 
    $('#<%=subcomment.id%>').find(".morelink").click(function(){
        if($(this).hasClass("less")) {
            $(this).removeClass("less");
            $(this).html(moretext);
        } else {
            $(this).addClass("less");
            $(this).html(lesstext);
        }
        $(this).parent().prev().toggle();
        $(this).prev().toggle();
        return false;
    });
    $('.loading-reply-indicator').hide();
    $('#<%=subcomment.parent_comment.try(:id)%>').find('.subcomments_count').text(<%=subcomment.parent_comment.try(:subcomments).try(:count)%>)
    $('.load-more-replies').unbind().click(function() {
      $(this).parent().find('.subcomment-post:hidden').slice(0,3).show();
      $(this).find('.loading-reply-indicator').show().delay(100).fadeOut();
      if (!$(this).parent().find('.subcomment-post:hidden').length) {
        $(this).toggle();
      }
    });
  })
</script>
<%@subcomment = subcomment if subcomment%>
<%if @subcomment.parent_comment.subcomments.count>3 && @subcomment.parent_comment.subcomments.order(created_at: :desc).first.eql?(@subcomment)%>
  <div class="load-more-replies col-md-12">
    <%= link_to 'Load more replies', '', remote: true, style: "color:#fe8637"%>
    <span class="loading-reply-indicator">
    <%= image_tag("comment_loader.gif", class: "loading-reply-indicator") %>
    </span>
  </div>
<%end%>
<div id=<%=@subcomment.id%>>
  <div class="col-md-12 subcomment-post">
    <div class="image col-md-4" style="max-height: 30px; max-width: 30px;">
      <% src = "profpic_#{@subcomment.employee.gender.downcase}_index.jpg" %>
      <% src = @subcomment.employee.user.image_url(:thumb) if (@subcomment.employee.user.image_url rescue false) %>
      <%= image_tag src, size: "30x30", alt: " "%>
    </div>
    <div class="col-md-12" style="margin-left: 15px;width: 457px;word-wrap: break-word;">
      <span><b style="color: #fe8637"><%=@subcomment.employee.full_name%></b></span>
      <% if @subcomment.employee == @employee || @employee.is_admin || @post.employee == @employee  %>
        <ul class="nav navbar-nav navbar-right edit-comment pull-right">
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" style="background-color: #f7f7f7;;padding: 2px;">
            <b class="caret"></b></a>
              <ul class="dropdown-menu">
              <% if @subcomment.employee == @employee %>
                <li><%= link_to 'Edit reply', edit_company_employee_post_comment_path(@company, @employee, @post, @subcomment), remote: true %></li>
              <%end%>
                <li><%= link_to 'Delete reply', company_employee_post_comment_path(@company, @employee, @post, @subcomment), method: :delete, remote: true %></li>
              </ul>
          </li>
        </ul>
      <%end%>
      <span class="more"><%=@subcomment.description%></span>
      <div class="subcomment-actions col-md-12">
        <%@employee_comment_likes = Employee::Like.where(comment_id: @subcomment.id, employee_id: @employee.id)%>
        <%if @employee_comment_likes.present?%>
          <%@like=@employee_comment_likes.first.id.to_s%>
        <%end%>
        <% if @employee_comment_likes.count.eql?(0) %>
          <%=link_to 'Like', company_employee_likes_path(@company, @employee, @subcomment), method: :post, remote: true, class: "like-btn"%></span>
        <% else%>
          <%=link_to 'Unlike', company_employee_like_path(@company, @employee, @like, @subcomment), method: :delete, remote: true, class: "like-btn"%></span>
        <%end%>
        <%=link_to '', company_employee_show_all_likes_path(@company, @employee, @subcomment), remote: true, class: "fa fa-thumbs-o-up thumsup-icon", style: "color: black"%>
        <span class="likes_count"><%=Employee::Like.where(comment_id: @subcomment.id, employee_id: @employee.id).count%></span>
        <span style="margin-left: 9px;"><%=time_ago_in_words(@subcomment.updated_at)%></span>
      </div>
    </div>
  </div>
</div>

app/views/user/comments/_subcomment_form.html.erb
<script>
  $(function () {
    $('#<%=@subcomment.id%>-edit-subcomment-modal').modal();
    $('.employee_subcomment_description').on('keypress',function(){
      $(this).css('height','auto');
      $(this).height(this.scrollHeight);
    });
    $('.employee_subcomment_description').keypress(function(e){
      if(e.which == 13){
        $(this).closest('form').submit();
        $('.modal-header button.close').trigger('click');
       }
      });
  });
</script>
<div style="overflow-y: auto;">
  <div id="<%=@subcomment.id%>-edit-subcomment-modal" class="modal fade colored-header" tabindex="-1" role="dialog">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <h3>Edit Reply</h3>
          <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
        </div>
        <div class="modal-body" style="max-height: 450px;overflow-y: auto;">
          <%= form_for @subcomment, remote: true, url: company_employee_post_comment_path(@company, @employee, @post, @subcomment), html: {class: 'form-horizontal', id: 'edit-subcomment-form'} do |f| %>
            <%= f.hidden_field :parent_comment, value: @comment.id%>
            <div class="col-md-12 user-post" style="margin-top: 0px;">
              <div class="image" style="max-height: 48px; max-width: 48px;">
                <% src = "profpic_#{@employee.gender.downcase}_index.jpg" %>
                <% src = @employee.user.image_url(:thumb) if (@employee.user.image_url rescue false) %>
                <%= image_tag src, size: "48x48", alt: " "%>
              </div>
              <div class="post-box" style="float:right;">
                <%=f.text_area :description, class: "form-control employee_subcomment_description", placeholder: "Press Enter to Write a reply..", size: "3x2", style:"overflow:hidden;resize: none;",id: "#{@subcomment.id.to_s}-input"%>
                <span style="display: none;"><%=f.submit%></span>
                <span style="float: right;">Press Enter to Write a Reply</span>
              </div>
            </div>
          <%end%>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/user/comments/create.js.erb
<% if params.require(:user_comment).permit(:parent_comment).present?%>
  parent_id = '<%=params.require(:user_comment).permit(:parent_comment).values[0]%>'
  $('#subcomment_data'+parent_id).find('.load-more-replies').remove();
  $('#subcomment_data'+parent_id).prepend('<%= j render partial: 'subcomment', locals: { :subcomment => @comment } %>');
  $('#subcomment_data'+parent_id).find('.subcomment-post').hide();
  $('#subcomment_data'+parent_id).find('.subcomment-post').slice(0,3).show();
  $('.employee_subcomment_description').val('')
<%else%>
  id = '<%=params[:post_id]%>';
  $('#comment_data'+id).find('.load-more-comments').remove();
  $('#comment_data'+id).prepend('<%= j render @comment %>');
  $('#comment_data'+id).find('.comment-post').hide();
  $('#comment_data'+id).find('.comment-post').slice(0,3).show();
  $('.employee_comment_description').val('')
<%end%>

app/views/user/comments/destroy.js.erb
<%if @comment.parent_comment.present?%>
  parent_id = '<%=@comment.parent_comment_id%>'
  $('#<%=@comment.parent_comment.try(:id)%>').find('.subcomments_count').text(<%=@comment.parent_comment.try(:subcomments).try(:count)%>)
  <%if @comment.parent_comment.subcomments.count<4 %>
    $('#subcomment_data<%=@comment.parent_comment.id%>').find('.load-more-replies').remove();
  <%end%>
  $('#<%=@comment.id%>').remove();
  $('#subcomment_data<%=@comment.parent_comment.id%>').find('.subcomment-post').hide();
  $('#subcomment_data<%=@comment.parent_comment.id%>').find('.subcomment-post').slice(0,3).show();
<%else%>
  $('#<%=@post.id%>').find('.comments_count').text(<%=@post.comments.where(parent_comment_id: nil).count%>)
  <%if @comment.post.comments.where(parent_comment_id: nil).count<4 %>
    $('#comment_data<%=@comment.post.id%>').find('.load-more-comments').remove();
  <%end%>
  $('#<%=@comment.id%>').remove();
  $('#comment_data<%=@comment.post.id%>').find('.comment-post').hide();
  $('#comment_data<%=@comment.post.id%>').find('.comment-post').slice(0,3).show();
<%end%>

app/views/user/comments/edit.js.erb
<%if @comment.parent_comment.present?%>
  parent_id = '<%=@comment.parent_comment_id%>'
  id = '<%=params[:id]%>';
  $('#empty').html("<%= j render partial: 'subcomment_form', locals: { :@subcomment => Employee::Comment.find(params[:id]) } %>");
<%else%>
  id = '<%=params[:post_id]%>';
  id = '<%=params[:id]%>';
  $('#empty').html("<%= j render partial: 'form', locals: { :@comment => Employee::Comment.find(params[:id]) } %>");
<%end%>

app/views/user/comments/show_all_comments.js.erb
$modal = $("#show-comments-modal");
$modal.modal();
<%if @post_item%>
  $modal.find('.modal-body').html("<%= j render :partial => 'shared/like_comment_data', collection: Employee::Comment.all.where(post_id: @post_item.id).map(&:employee).uniq, as: :employee %>");
<% else %>
  $modal.find('.modal-body').html("<%= j render :partial => 'shared/like_comment_data', collection: Employee::Comment.all.where(comment_id: @comment_item.id).map(&:employee).uniq, as: :employee %>");
<%end%>